server:
  port: ${AVC_SERVER_PORT:8080}

spring:
  datasource:
    # 文件模式 H2，去掉 AUTO_SERVER 与 DB_CLOSE_ON_EXIT 以兼容 2.x 版本
    # 保留 DB_CLOSE_DELAY=-1 保证连接关闭后不立即卸载, MODE=MySQL 方便未来迁移
    url: ${AVC_DATASOURCE_URL:jdbc:h2:file:./data/visiondb;MODE=MySQL;DB_CLOSE_DELAY=-1}
    driver-class-name: ${AVC_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${AVC_DATASOURCE_USERNAME:sa}
    password: ${AVC_DATASOURCE_PASSWORD:}
  jpa:
    database-platform: ${AVC_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${AVC_JPA_HIBERNATE_DDL_AUTO:update}
  h2:
    console:
      enabled: ${AVC_H2_CONSOLE_ENABLED:true}

# 预测服务配置
predict:
  api:
    url: ${AVC_PREDICT_API_URL:http://localhost:50000/predict}
    prediction-length: ${AVC_PREDICT_API_PREDICTION_LENGTH:60}
    history-length: ${AVC_PREDICT_API_HISTORY_LENGTH:300}
  cache:
    enabled: ${AVC_PREDICT_CACHE_ENABLED:true}
    prefetch-interval-ms: ${AVC_PREDICT_CACHE_PREFETCH_INTERVAL_MS:30000}
    min-ahead-minutes: ${AVC_PREDICT_CACHE_MIN_AHEAD_MINUTES:2}
    tolerance-ms: ${AVC_PREDICT_CACHE_TOLERANCE_MS:30000}
    max-points-per-tag: ${AVC_PREDICT_CACHE_MAX_POINTS_PER_TAG:5000}

# 数据视图/接口配置
data:
  api:
    history-limit: ${AVC_DATA_API_HISTORY_LIMIT:200}
  view:
    latest-minutes-window: ${AVC_DATA_VIEW_LATEST_MINUTES_WINDOW:5}
  tag-history:
    default-minutes: ${AVC_DATA_TAG_HISTORY_DEFAULT_MINUTES:3}

# IoTDB 连接配置
iotdb:
  host: ${AVC_IOTDB_HOST:127.0.0.1}
  port: ${AVC_IOTDB_PORT:6667}
  username: ${AVC_IOTDB_USERNAME:root}
  password: ${AVC_IOTDB_PASSWORD:root}
  rt:
    db: ${AVC_IOTDB_RT_DB:rt}
    # TTL 为 1 天（毫秒） 7 * 24 * 60 * 60 * 1000L
    ttl: ${AVC_IOTDB_RT_TTL:86400000}

# 预警功能 (MVP 阈值+预测偏差)
alert:
  enabled: ${AVC_ALERT_ENABLED:true}
  scan-interval-ms: ${AVC_ALERT_SCAN_INTERVAL_MS:60000} # 定时扫描间隔
  duplicate-suppress-minutes: ${AVC_ALERT_DUP_SUPPRESS_MINUTES:5} # 5 分钟内相同签名不重复
  prediction-enabled: ${AVC_ALERT_PREDICTION_ENABLED:true} # 启用预测基线/偏差逻辑
  deviation-percent-threshold: ${AVC_ALERT_DEVIATION_PERCENT_THRESHOLD:15} # (当前-预测)/预测 *100 超过此百分比则触发偏差预警

logging:
  level:
    aiot.vision.collector: ${AVC_LOGGING_LEVEL_APP:INFO}
